---
- name: Launch dynamic inventory script for Parallels
  hosts: localhost
  become: no
  gather_facts: false

  tasks:
  - name: Copy dyn_inventory.sh to Controller
    ansible.builtin.copy:
      src: dyn_inventory.sh
      dest: /tmp/dyn_inventory.sh
      owner: root
      group: root
      mode: '0644'
  