---
- name: Launch dynamic inventory script for Parallels
  hosts: MacBook-Pro
  become: no
  gather_facts: false

  tasks:
  - name: Copy dyn_inventory.sh to Controller
    ansible.builtin.copy:
      src: dyn_inventory.sh
      dest: /tmp/dyn_inventory.sh
      owner: jboivie
      group: jboivie
      mode: '0644'
  