---
- name: Launch dynamic inventory script for Parallels
  hosts: MacBook-Pro
  become: no
  gather_facts: false

  tasks:
  - name: Copy dyn_inventory.sh to Controller
    ansible.builtin.copy:
      src: dyn_inventory.sh
      dest: /tmp/dyn_inventory.sh
      owner: jboivie
      group: wheel
      mode: "0740"
  - name: Execute the command in remote shell; stdout goes to the specified file on the remote
    ansible.builtin.shell: "source /tmp/dyn_inventory.sh > /tmp/dyn_inventory"