---
- name: Create dynamic inventory from prlctl
  hosts: MacBook-Pro
  become: no
  gather_facts: false

  tasks:
  - name: Get running VMs hostnames
    ansible.builtin.shell:
      cmd: "/usr/local/bin/prlctl list | /usr/bin/awk -v col=4 '{print $col}' | /usr/bin/awk 'NR>1'"
    register: prtctl_vmlist

  - name: Debug
    ansible.builtin.debug:
      msg: "{{ prtctl_vmlist.stdout_lines }}"

  - name: Get running VMs IP addresses
    ansible.builtin.shell:
      cmd: "/usr/local/bin/prlctl exec {{item}} ip -4 -br addr show enp0s5 | /usr/bin/awk '{print $3}' | cut -d / -f 1"
    with_items: "{{ prtctl_vmlist.stdout_lines }}"
    register: prlctl_iplist

  - name: Debug
    ansible.builtin.debug:
      msg: "{{ prlctl_iplist.stdout_lines }}"