---
- name: Create dynamic inventory from prlctl
  hosts: MacBook-Pro
  become: no
  gather_facts: false

  tasks:
  - name: Get running VMs hostnames
    ansible.builtin.shell:
      cmd: "/usr/local/bin/prlctl list | /usr/bin/awk -v col=4 '{print $col}' | /usr/bin/awk 'NR>1'"
    register: hostnames

  - name: Debug
    ansible.builtin.debug: 
      msg: "{{ hostnames.stdout_lines }}"